# Generated by Django 2.0.6 on 2018-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
