# Generated by Django 2.0.6 on 2018-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reply',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
