# Generated by Django 2.0.6 on 2018-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180703_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='city',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='country',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='photo/thumb'),
        ),
    ]
