# Generated by Django 2.0.6 on 2018-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180703_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
