# Generated by Django 2.0.6 on 2018-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='head',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='head',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='head',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
